baseURL = "https://arthurkauffman.com/"
footnoteReturnLinkContents = "↩"
languageCode = "en-us"
title = "Arthur Kauffman"
theme = "noteworthy"
paginate = 10
summaryLength = 20

[author]
  name = "Arthur Kauffman"

[params]
  description = "Take issue with pants"
  github = "https://github.com/a1kn"
  wordpress = "https://arthurlyle.com/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 2

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true 
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
